eventex/urls.py
from django.contrib import admin
from core.views import home
from django.urls import path, include

urlpatterns = [
    path('', home, name='home'),
    path('inscricao/', include('subscriptions.urls')),
    path('admin/', admin.site.urls),
]

subscriptions/urls.py
from django.urls import path

from subscriptions.views import new, detail

app_name = 'subscriptions'

urlpatterns = [
    path('', new, name='new'),
    path('<int:pk>/', detail, name='detail'),
]

core/models.py
from django.db import models

# Create your models here.

subscriptions/models.py
from django.db import models


class Subscription(models.Model):
    name = models.CharField('nome', max_length=200)
    cpf = models.CharField('CPF', max_length=11)
    email = models.EmailField('e-mail')
    phone = models.CharField('telefone', max_length=20)
    created_at = models.DateTimeField('cadastrado em', auto_now_add=True)
    paid = models.BooleanField('pago', default=False)

    class Meta:
        verbose_name_plural = 'inscrições'
        verbose_name = 'inscrição'
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

subscriptions/forms.py
from django import forms
from django.core.exceptions import ValidationError


def validar_cpf(value):
    if not value.isdigit():
        raise ValidationError('Seu CPF deve conter apenas números', 'digitos')

    if len(value) != 11:
        raise ValidationError('CPF deve conter exatamente 11 números', 'tamanho')


class SubscriptionForm(forms.Form):
    name = forms.CharField(label='Nome')
    cpf = forms.CharField(label='CPF', validators=[validar_cpf])
    email = forms.EmailField(label='E-mail')
    phone = forms.CharField(label='Telefone')

    def clean_name(self):
        name = self.cleaned_data['name']

        palavras = []
        for p in name.split():
            palavras.append(p.capitalize())

        return ' '.join(palavras)

core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'index.html')
# Create your views here.

subscriptions/views.py
from django.conf import settings
from django.core import mail
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, resolve_url as r
from django.template.loader import render_to_string
from subscriptions.forms import SubscriptionForm
from subscriptions.models import Subscription


def new(request):
    if request.method == 'POST':
        return create(request)

    return empty_form(request)


def empty_form(request):
    return render(request, 'subscriptions/subscription_form.html',
                  {'form': SubscriptionForm()})


def create(request):
    form = SubscriptionForm(request.POST)

    if not form.is_valid():
        return render(request, 'subscriptions/subscription_form.html',
                      {'form': form})
    subscription = Subscription.objects.create(**form.cleaned_data)

    # Envio do e-mail
    _send_mail('Confirmação de inscrição',
               settings.DEFAULT_FROM_EMAIL,
               subscription.email,
               'subscriptions/subscription_email.txt',
               {'subscription': subscription})

    return HttpResponseRedirect(r('subscriptions:detail', subscription.pk))


def detail(request, pk):
    try:
        subscription = Subscription.objects.get(pk=pk)

    except Subscription.DoesNotExist:
        raise Http404

    return render(request, 'subscriptions/subscription_detail.html',
                  {'subscription': subscription})


def _send_mail(subject, from_, to, template_name, context):
    body = render_to_string(template_name, context)
    mail.send_mail(subject, body, from_, [from_, to])

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
        <title>{% block title %}Eventex - O maior encontro hacker do mundo!{% endblock title %}</title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="Eventex - O maior encontro hacker do mundo!">
        <meta name="author" content="wttd">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/basalstyle/style.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <link href='http://fonts.googleapis.com/css?family=Economica:400,700' rel='stylesheet' type='text/css'>
	</head>

	<body>
        <div class="header-frame row">
                <header class="header header-inline min-h-3 row desktop-12 container" role="banner">

                        <div class="site-logo">
                                <h1><a href="{% url 'home' %}" rel="home">Eventex</h1>
                                <p class="site-description screen-reader-only">O maior encontro hacker do mundo!</p>
                        </div>

                        <nav class="nav-inline" role="navigation">
                                <a href="javascript:void(0);" class="nav-mobile"><i class="fa fa-bars"></i></a>
                                <ul>
                                        <li><a data-scroll href="{% url 'home' %}#overview">Conferência</a></li>
                                        <li><a data-scroll href="{% url 'home' %}#sponsors">Patrocinadores</a></li>
                                        <li><a data-scroll href="{% url 'home' %}#register">Inscrição</a></li>
                                        <li><a data-scroll href="{% url 'home' %}#evenue">Local</a></li>
                                </ul>
                        </nav>

                </header>
        </div>

        {% block content %}
        {% endblock content %}

    </body>
</html>

core/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
        <title>Eventex - O maior encontro hacker do mundo!</title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="Eventex - O maior encontro hacker do mundo!">
        <meta name="author" content="wttd">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/basalstyle/style.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <link href='http://fonts.googleapis.com/css?family=Economica:400,700' rel='stylesheet' type='text/css'>

        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>


        <script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
        <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
        <script src="{% static 'js/smooth-scroll.js' %}"></script>
        <script src="{% static 'js/retina-1.1.0.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>


	</head>

	<body>

        <div class="header-frame header-frame-absolute  row">
            <header class="header header-inline min-h-3 row desktop-12 container" role="banner">

                <div class="site-logo">
                    <h1><a href="{% url 'home' %}" rel="home">Eventex</a></h1>
                    <p class="site-description screen-reader-only">O maior encontro hacker do mundo!</p>
                </div>

                <nav class="nav-inline" role="navigation">
                    <a href="javascript:void(0);" class="nav-mobile"><i class="fa fa-bars"></i></a>
                    <ul>
                        <li><a data-scroll href="#overview">Conferência</a></li>
                        <li><a data-scroll href="#sponsors">Patrocinadores</a></li>
                        <li><a data-scroll href="#register">Inscrição</a></li>
                        <li><a data-scroll href="#venue">Local</a></li>
                    </ul>
                </nav>

            </header>
        </div>

      	<!-- TOP -->
        <section id="top" data-stellar-background-ratio="0.5">
        	<div class="countdown text-align-center row desktop-12 container">
            	<h1 class="uppercase">Eventex</h1>
                <h3>Brasil</h3>
            </div>
        </section>

        <!-- OVERVIEW -->
        <section id="overview">
        	<div class="overview text-align-center row desktop-12 min-h-15 padding-top-2 container">
            	<i class="fa fa-5x fa-globe"></i>
            	<h2>A Conferência</h2>
                <p class="lead">A maior reunião de hackers do mundo.<br>Reunindo profissionais e entusiastas dos quatro <br>cantos do planeta, o <em>Eventex</em> é o lugar onde você precisa estar.</p>
            	<p><a class="btn-basic btn-blue" data-scroll href="#register">Garanta a sua vaga!</a></p>
            </div>
        </section>

        <!-- SPONSORS -->
        <section id="sponsors">
        	<div class="sponsors text-align-center row desktop-12 min-h-28 padding-bottom-2 container">

                <h2>Patrocinadores</h2>

                <h3>Gold</h3>
                <div class="sponsor-slider min-h-6">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-01.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-02.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-03.png' %}" alt="logo">

                </div>

                <h3>Silver</h3>
                <div class="sponsor-slider min-h-6 margin-bottom-1">
                	<img class="img-responsive" src="{% static 'img/sponsor-silver-01.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-02.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-03.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-04.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-05.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-06.png' %}" alt="logo">
                </div>

                <h3>Seja um patrocinador</h3>
                <p>Interessado? Descubra as oportunidades e benefícios.</p>
                <a class="btn-basic btn-blue" href="mailto:contato@eventex.com.br?Subject=Patrocínio">informe-se</a>

            </div>
        </section>

        <!-- REGISTER -->
        <section id="register">
            <div class="register row">
                <div class="text-align-center row desktop-12 padding-top-2 min-h-14 container">
                	<h2>Inscrição</h2>
                	<h3>Inscrições em breve!</h3>
                    <p>Fique à vontade para entrar em contato com a gente.<br>Teremos prazer em responder quaisquer dúvidas.</p>
                	<a class="btn-basic btn-blue" href="{% url 'subscriptions:new' %}">Inscricao</a>
                </div>
            </div>
        </section>

        <!-- VENUE -->
        <section id="venue">
            <div class="row min-h-10">

                <div id="map-canvas"></div>
                <div class="row desktop-12 container">
                    <div class="venue row">
                        <div class="venue-address desktop-4 gutter">
                            <h2>Bar Samba Caffé</h2>
                            <p>Melhor que qualquer centro de convenções.</p>
                            <p class="address">
                                <i class="fa fa-2x fa-map-marker fa-inverse"></i>
                                Rua do Ouvidor 23, Centro<br>
                                Rio de Janeiro, RJ
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </body>
</html>

subscriptions/templates/subscriptions/subscription_detail.html
{% extends 'base.html' %}

{% block content %}
<!-- OVERVIEW -->
        <section>
            <div class="content row padding-bottom-3 desktop-12 container">
                <h1>Obrigado por se inscrever!</h1>
                <div class="desktop-6">
                	<p>Estes foram os dados que você nos forneceu em sua inscrição:</p>

					<ul>
						<li>Nome: {{ subscription.name }}</li>
						<li>CPF: {{ subscription.cpf }}</li>
						<li>Email: {{ subscription.email }}</li>
						<li>Telefone: {{ subscription.phone }}</li>
					</ul>

					<p>Em até 48 horas úteis, a nossa equipe entrará em contato com você para concluirmos a sua matrícula.</p>

                </div>
            </div>
        </section>
{% endblock content %}>

subscriptions/templates/subscriptions/subscription_form.html
{% extends 'base.html' %}

{% block content %}
<!-- OVERVIEW -->
<section>
    <div class="content row padding-bottom-3 desktop-12 container">
        <h1>Formulário de Inscrição</h1>
        <div class="desktop-6">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert sucess">
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="." novalidate method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-row label-block input-text">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                    {{ form.name.errors }}
                    {{ form.name }}
                </div>
                <div class="form-row label-block input-text">
                    <label for="{{ form.cpf.id_for_label }}">{{ form.cpf.label }}</label>
                    {{ form.cpf.errors }}
                    {{ form.cpf }}
                </div>
                <div class="form-row label-block input-text">
                    <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                    {{ form.email.errors }}
                    {{ form.email }}
                </div>
                <div class="form-row label-block input-text">
                    <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
                    {{ form.phone.errors }}
                    {{ form.phone }}
                </div>
                <p class="btn-row"><input type="submit" value="Enviar!"/></p>
            </form>
        </div>
    </div>
</section>
{% endblock content %}